### ISSUE TITLE
Please push latest code

### ISSUE THREAD

**Issue by erw13n** [2sic/eav-server#16]
Hi @iJungleboy 

Can you push eav-server latest code? I got error at "ToSIC_SexyContent\Environtment\Dnn7\DataSources\DnnUserProfileDataSource"

![image](https://user-images.githubusercontent.com/792847/33919368-f79a43da-dfea-11e7-8e43-e6fab4f14ea9.png)

**Comment by iJungleboy** [comment]
i think I just did -  otherwise try the dev-branch

**Comment by erw13n** [comment]
Build successful, thx
